/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef _LINUX_MFD_SYSCON_NOVATEK_SRAMCTRL_H
#define _LINUX_MFD_SYSCON_NOVATEK_SRAMCTRL_H

#include <linux/bits.h>

#define NOVATEK_SRAM_SHUTDOWN		0x00
#define NOVATEK_SRAM_FSPI_SD_MASK	BIT(17)
#define NOVATEK_SRAM_FSPI_ENABLE	0x0
#define NOVATEK_SRAM_FSPI_DISABLE	0x1
#define NOVATEK_SRAM_ETH_SD_MASK	BIT(18)
#define NOVATEK_SRAM_ETH_ENABLE		0x0
#define NOVATEK_SRAM_ETH_DISABLE	0x1
#define NOVATEK_SRAM_USB_SD_MASK	BIT(19)
#define NOVATEK_SRAM_USB_ENABLE		0x0
#define NOVATEK_SRAM_USB_DISABLE	0x1
#define NOVATEK_SRAM_RSA_SD_MASK	BIT(25)
#define NOVATEK_SRAM_RSA_ENABLE		0x0
#define NOVATEK_SRAM_RSA_DISABLE	0x1
#define NOVATEK_SRAM_SDIO3_SD_MASK	BIT(31)
#define NOVATEK_SRAM_SDIO3_ENABLE	0x0
#define NOVATEK_SRAM_SDIO3_DISABLE	0x1

#endif /* _LINUX_MFD_SYSCON_NOVATEK_SRAMCTRL_H */
