/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef __LINUX_MFD_NOVATEK_RTCSYS_H
#define __LINUX_MFD_NOVATEK_RTCSYS_H

#include <linux/bits.h>
#include <linux/mutex.h>

struct regmap;

#define NOVATEK_RTC_TIMER			0x00
#define NOVATEK_RTC_TIMER_SECOND_MASK		GENMASK(5, 0)
#define NOVATEK_RTC_TIMER_MINUTE_MASK		GENMASK(11, 6)
#define NOVATEK_RTC_TIMER_HOUR_MASK		GENMASK(16, 12)
#define NOVATEK_RTC_TIMER_TIME_MASK		GENMASK(16, 0)

#define NOVATEK_RTC_DAYKEY			0x04
#define NOVATEK_RTC_DAYKEY_DAY_MASK		GENMASK(15, 0)
#define NOVATEK_RTC_DAYKEY_KEY_MASK		GENMASK(19, 16)
#define NOVATEK_RTC_KEY_VALID			0xa
#define NOVATEK_RTC_KEY_POWER_LOST		BIT(0)

#define NOVATEK_RTC_ALARM			0x08
#define NOVATEK_RTC_ALARM_SECOND_MASK		GENMASK(5, 0)
#define NOVATEK_RTC_ALARM_MINUTE_MASK		GENMASK(11, 6)
#define NOVATEK_RTC_ALARM_HOUR_MASK		GENMASK(16, 12)

#define NOVATEK_RTC_STATUS			0x0c
#define NOVATEK_RTC_STATUS_ALARM_MASK		BIT(0)
#define NOVATEK_RTC_STATUS_SRST_MASK		BIT(1)
#define NOVATEK_RTC_STATUS_READY_MASK		BIT(2)
#define NOVATEK_RTC_STATUS_CSET_MASK		BIT(8)

#define NOVATEK_RTC_CTRL			0x10
#define NOVATEK_RTC_CTRL_ALARM_INTEN_MASK	BIT(0)
#define NOVATEK_RTC_CTRL_SRST_MASK		BIT(1)
#define NOVATEK_RTC_CTRL_CSET_MASK		BIT(2)
#define NOVATEK_RTC_CTRL_TIME_SEL_MASK		BIT(3)
#define NOVATEK_RTC_CTRL_DAY_SEL_MASK		BIT(4)
#define NOVATEK_RTC_CTRL_KEY_SEL_MASK		BIT(5)
#define NOVATEK_RTC_CTRL_PWRALARMTIME_SEL_MASK	BIT(6)
#define NOVATEK_RTC_CTRL_PWRALARMDAY_SEL_MASK	BIT(7)
#define NOVATEK_RTC_CTRL_CSET_INTEN_MASK	BIT(8)
#define NOVATEK_RTC_CTRL_DATA0_SEL_MASK		BIT(12)
#define NOVATEK_RTC_CTRL_PWR_EN2_CONFIG_MASK	BIT(16)
#define NOVATEK_RTC_CTRL_PWR_EN3_SEL_MASK	BIT(17)

#define NOVATEK_RTC_DATA			0x14
#define NOVATEK_RTC_DATA0_MASK			GENMASK(7, 0)

#define NOVATEK_RTC_PWBC			0x18
#define NOVATEK_RTC_PWBC_RESET_SDT_TIMER_MASK	BIT(0)
#define NOVATEK_RTC_PWBC_PWR_OFF_MASK		BIT(1)
#define NOVATEK_RTC_PWBC_PWRALARM_EN_MASK	BIT(3)
#define NOVATEK_RTC_PWBC_PWRALARM_DIS_MASK	BIT(4)
#define NOVATEK_RTC_PWBC_PWR_EN2_LATCH_MASK	BIT(5)
#define NOVATEK_RTC_PWBC_PWR_EN3_CTRL_MASK	BIT(6)
#define NOVATEK_RTC_PWBC_PWR_SW1_INTEN_MASK	BIT(24)
#define NOVATEK_RTC_PWBC_PWR_SW2_INTEN_MASK	BIT(25)
#define NOVATEK_RTC_PWBC_COMMAND_MASK				\
	(NOVATEK_RTC_PWBC_RESET_SDT_TIMER_MASK |		\
	 NOVATEK_RTC_PWBC_PWR_OFF_MASK |			\
	 NOVATEK_RTC_PWBC_PWRALARM_EN_MASK |			\
	 NOVATEK_RTC_PWBC_PWRALARM_DIS_MASK |			\
	 NOVATEK_RTC_PWBC_PWR_EN2_LATCH_MASK)

#define NOVATEK_RTC_PWBCSTS			0x1c
#define NOVATEK_RTC_PWBCSTS_PWRALARM_EN_MASK	BIT(0)
#define NOVATEK_RTC_PWBCSTS_COREPWR_VALID_MASK	BIT(1)
#define NOVATEK_RTC_PWBCSTS_PWRONSRC_SW1_MASK	BIT(8)
#define NOVATEK_RTC_PWBCSTS_PWRONSRC_SW2_MASK	BIT(9)
#define NOVATEK_RTC_PWBCSTS_PWRONSRC_SW3_MASK	BIT(10)
#define NOVATEK_RTC_PWBCSTS_PWRONSRC_SW4_MASK	BIT(11)
#define NOVATEK_RTC_PWBCSTS_PWRON_PWR_EN2_MASK	BIT(12)
#define NOVATEK_RTC_PWBCSTS_PWRALARM_SRC_MASK	BIT(15)
#define NOVATEK_RTC_PWBCSTS_PWR_SW1_PIN_MASK	BIT(16)
#define NOVATEK_RTC_PWBCSTS_PWR_SW2_PIN_MASK	BIT(17)
#define NOVATEK_RTC_PWBCSTS_PWR_SW3_PIN_MASK	BIT(18)
#define NOVATEK_RTC_PWBCSTS_PWR_SW4_PIN_MASK	BIT(19)
#define NOVATEK_RTC_PWBCSTS_PWR_SW1_STATUS_MASK	BIT(24)
#define NOVATEK_RTC_PWBCSTS_PWR_SW2_STATUS_MASK	BIT(25)

#define NOVATEK_RTC_PWRALM			0x20
#define NOVATEK_RTC_PWRALM_SECOND_MASK		GENMASK(5, 0)
#define NOVATEK_RTC_PWRALM_MINUTE_MASK		GENMASK(11, 6)
#define NOVATEK_RTC_PWRALM_HOUR_MASK		GENMASK(16, 12)
#define NOVATEK_RTC_PWRALM_DAY_MASK		GENMASK(24, 20)

#define NOVATEK_RTC_OSCAN			0x24
#define NOVATEK_RTC_OSCAN_CONFIG_MASK		GENMASK(7, 0)
#define NOVATEK_RTC_OSCAN_CONFIG		0x09

enum novatek_rtcsys_irq {
	NOVATEK_RTCSYS_IRQ_ALARM,
	NOVATEK_RTCSYS_IRQ_CSET,
	NOVATEK_RTCSYS_IRQ_NUM,
};

struct novatek_rtcsys {
	struct regmap *regmap;
	/* Serialize multi-register RTC and power-control transactions. */
	struct mutex lock;
};

#endif /* __LINUX_MFD_NOVATEK_RTCSYS_H */
